# Generated by Django 5.2.5 on 2025-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_remove_hackathon_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='prizes',
            field=models.JSONField(default=dict, help_text="{'first': 50000, 'second': 30000}"),
        ),
    ]
