# Generated by Django 5.2.5 on 2025-08-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_alter_hackathon_prizes'),
        ('teams', '0001_initial'),
        ('users', '0004_rename_total_hackathons_user_total_hackathons_participated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_hackathon',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathons.hackathon'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
